apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap
spec:
  selector:
    matchLabels:
      app: ap
  replicas: 1
  template:
    metadata:
      labels:
        app: ap
    spec:
      containers:
        - name: ap
          image: sentence-ap:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 9080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9080
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ap-service
spec:
  selector:
    app: ap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ap-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ap-service
              servicePort: 80
