version: '3'
services:
  app:
    build: .
    ports: [9080:9080]
    command: sleep infinity
    volumes:
      - type: bind
        source: /mnt/c/github/sentence-diagram/card-service
        target: /workspace
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432